#!/usr/bin/env ruby
require "rubygems"

ROOT_DIR = "/home/johnryding/johnryding.com"

# Check out the git repo if it's a new machine
unless File.directory?("#{ROOT_DIR}/.git") then
  puts "STATUS: Cloning johnryding.com git repo....."
  `git clone git@github.com:strife25/johnryding.com.git #{ROOT_DIR}/`
  `git remote add upstream git@github.com:strife25/johnryding.com.git`
  puts "STATUS: Git clone done"
end

# Get latest updates from git
puts "STATUS: Pulling in latest changes..."
`git fetch upstream`
`git merge upstream/master`
puts "STATUS: Git pull done."

puts "STATUS: Installing project gems...."
unless Gem.available?("bundler") then
  `gem install bundler --no-ri --no-rdoc -q`
end

`bundle install --quiet`
puts "STATUS: Gem installation complete."

# Restart Passenger
unless File.directory?("#{ROOT_DIR}/tmp") then
  Dir.mkdir("#{ROOT_DIR}/tmp")
end

`touch tmp/restart`
puts "STATUS: Restarted Passenger"


